"""Find PrestaShop products where an active catalog price rule is silently skipped
because the product already has its own manual specific price.

PrestaShop stores manual specific prices and catalog-rule-generated discounts in the
same specific_price table. Product::getPriceStatic(), through
SpecificPrice::getSpecificPrice(), always picks a manual row (id_specific_price_rule = 0)
ahead of a row generated by a catalog rule, even when the rule is active and the product
is in scope. This script never deletes or edits a merchant's manual override on its own.
It reports every affected product. Only with DRY_RUN=false, and only for the specific
specific_price ids a merchant selects, does it delete the chosen rows. Safe to run
again and again.

Guide: https://www.allanninal.dev/prestashop/catalog-rule-skipped-by-specific-price/
"""
import os
import csv
import logging
import datetime
import requests

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("catalog_rule_skip_report")

BASE_URL = os.environ["PRESTASHOP_URL"].rstrip("/")
WS_KEY = os.environ["PRESTASHOP_WS_KEY"]
DRY_RUN = os.environ.get("DRY_RUN", "true").lower() == "true"
REPORT_PATH = os.environ.get("REPORT_PATH", "skipped_catalog_rules.csv")


def api_get(path, params=None):
    params = dict(params or {})
    params["output_format"] = "JSON"
    r = requests.get(f"{BASE_URL}/api/{path}", params=params, auth=(WS_KEY, ""), timeout=30)
    r.raise_for_status()
    return r.json()


def api_delete(path):
    r = requests.delete(
        f"{BASE_URL}/api/{path}",
        params={"output_format": "JSON"},
        auth=(WS_KEY, ""),
        timeout=30,
    )
    r.raise_for_status()
    return True


def _within_window(row, now):
    from_ok = not row.get("from") or row["from"] <= now
    to_ok = not row.get("to") or row["to"] >= now
    return from_ok and to_ok


def classify_skipped_product(product, rule_scope_product_ids, specific_price_rows, now, id_rule=None):
    """Pure decision function. No I/O.

    product: {"id_product": int}
    rule_scope_product_ids: set[int] of product ids targeted by the rule
    specific_price_rows: list of {"id_product", "id_specific_price_rule", "from", "to"}
    now: comparable string/datetime for "now", same format as from/to
    id_rule: optional int, the active rule's own id, to detect "rule_applied"

    Returns {"skipped": bool, "reason": str|None}.
    """
    id_product = product["id_product"]
    if id_product not in rule_scope_product_ids:
        return {"skipped": False, "reason": None}

    rows_for_product = [r for r in specific_price_rows if r["id_product"] == id_product]

    for row in rows_for_product:
        if row["id_specific_price_rule"] == 0 and _within_window(row, now):
            return {"skipped": True, "reason": "manual_specific_price_override_active"}

    if id_rule is not None:
        for row in rows_for_product:
            if row["id_specific_price_rule"] == id_rule:
                return {"skipped": False, "reason": "rule_applied"}

    return {"skipped": False, "reason": "no_override_found"}


def active_catalog_rules():
    data = api_get("specific_price_rules", {"filter[active]": "1", "display": "full"})
    rules = data.get("specific_price_rules") or []
    if isinstance(rules, dict):
        rules = [rules]
    return [
        {"id": int(r["id"]), "name": r["name"], "id_category": int(r["id_category"])}
        for r in rules
    ]


def product_ids_in_category(id_category):
    data = api_get("products", {"filter[id_category_default]": id_category, "display": "[id]"})
    products = data.get("products") or []
    if isinstance(products, dict):
        products = [products]
    return [int(p["id"]) for p in products]


def product_reference(id_product):
    data = api_get(f"products/{id_product}", {"display": "[reference]"})
    product = data.get("product") or {}
    return product.get("reference", "")


def specific_price_rows(id_product):
    data = api_get("specific_prices", {"filter[id_product]": id_product, "display": "full"})
    rows = data.get("specific_prices") or []
    if isinstance(rows, dict):
        rows = [rows]
    return [
        {
            "id_specific_price": int(r["id"]),
            "id_product": int(r["id_product"]),
            "id_specific_price_rule": int(r["id_specific_price_rule"]),
            "reduction": r.get("reduction"),
            "reduction_type": r.get("reduction_type"),
            "from": r.get("from") or None,
            "to": r.get("to") or None,
        }
        for r in rows
    ]


def delete_specific_price(id_specific_price):
    return api_delete(f"specific_prices/{id_specific_price}")


def build_report():
    now = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
    report_rows = []
    for rule in active_catalog_rules():
        scope_ids = set(product_ids_in_category(rule["id_category"]))
        for id_product in scope_ids:
            rows = specific_price_rows(id_product)
            result = classify_skipped_product(
                {"id_product": id_product}, scope_ids, rows, now, id_rule=rule["id"]
            )
            if not result["skipped"]:
                continue
            manual_row = next(
                r for r in rows
                if r["id_specific_price_rule"] == 0 and _within_window(r, now)
            )
            report_rows.append({
                "id_specific_price_rule": rule["id"],
                "rule_name": rule["name"],
                "id_product": id_product,
                "product_reference": product_reference(id_product),
                "manual_price_or_reduction": manual_row["reduction"],
                "id_specific_price": manual_row["id_specific_price"],
                "from": manual_row["from"],
                "to": manual_row["to"],
            })
    return report_rows


def write_report(report_rows, path):
    fieldnames = [
        "id_specific_price_rule", "rule_name", "id_product", "product_reference",
        "manual_price_or_reduction", "id_specific_price", "from", "to",
    ]
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(report_rows)


def run():
    report_rows = build_report()
    write_report(report_rows, REPORT_PATH)
    log.info("Found %d product(s) where a catalog rule is silently skipped.", len(report_rows))
    if DRY_RUN:
        log.info("DRY RUN: report written to %s. No specific_prices rows were touched.", REPORT_PATH)
    else:
        log.info(
            "DRY_RUN is false, but this script never bulk-deletes. "
            "Review %s, then call delete_specific_price(id_specific_price) "
            "only for the rows a merchant explicitly selects.",
            REPORT_PATH,
        )


if __name__ == "__main__":
    run()
